using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BOTManager.Entities.Utility
{
    public class Currency
    {
        public static string GetCurrency(string currency)
        {
            //// change the letter in lower format

            string lowerCurrency = currency.ToLowerInvariant();

            if (lowerCurrency.IndexOf("usd") >= 0)
                currency = "USD";
            else if (lowerCurrency.IndexOf("albanian lek") >= 0)
                currency = "ALL";
            else if (lowerCurrency.IndexOf("algerian dinar") >= 0)
                currency = "DZD";
            else if (lowerCurrency.IndexOf("aluminium ounces") >= 0)
                currency = "XAL";
            else if (lowerCurrency.IndexOf("argentine peso") >= 0)
                currency = "ARS";
            else if (lowerCurrency.IndexOf("aruba florin") >= 0)
                currency = "AWG";
            else if (lowerCurrency.IndexOf("australian dollar") >= 0)
                currency = "AUD";
            else if (lowerCurrency.IndexOf("bahamian dollar") >= 0)
                currency = "BSD";
            else if (lowerCurrency.IndexOf("bahraini dinar") >= 0)
                currency = "BHD";
            else if (lowerCurrency.IndexOf("bangladesh taka") >= 0)
                currency = "BDT";
            else if (lowerCurrency.IndexOf("barbados dollar") >= 0)
                currency = "BBD";
            else if (lowerCurrency.IndexOf("belarus ruble") >= 0)
                currency = "BYR";
            else if (lowerCurrency.IndexOf("belize dollar") >= 0)
                currency = "BZD";
            else if (lowerCurrency.IndexOf("bermuda dollar") >= 0)
                currency = "BMD";
            else if (lowerCurrency.IndexOf("bhutan ngultrum") >= 0)
                currency = "BTN";
            else if (lowerCurrency.IndexOf("bolivian boliviano") >= 0)
                currency = "BOB";
            else if (lowerCurrency.IndexOf("botswana pula") >= 0)
                currency = "BWP";
            else if (lowerCurrency.IndexOf("brazilian real") >= 0)
                currency = "BRL";
            else if (lowerCurrency.IndexOf("british pound") >= 0)
                currency = "GBP";
            else if (lowerCurrency.IndexOf("pound") >= 0)
                currency = "GBP";
            else if (lowerCurrency.IndexOf("brunei dollar") >= 0)
                currency = "BND";
            else if (lowerCurrency.IndexOf("bulgarian lev") >= 0)
                currency = "BGN";
            else if (lowerCurrency.IndexOf("burundi franc") >= 0)
                currency = "BIF";
            else if (lowerCurrency.IndexOf("cambodia riel") >= 0)
                currency = "KHR";
            else if (lowerCurrency.IndexOf("canadian dollar") >= 0)
                currency = "CAD";
            else if (lowerCurrency.IndexOf("cape verde escudo") >= 0)
                currency = "CVE";
            else if (lowerCurrency.IndexOf("cayman islands dollar") >= 0)
                currency = "KYD";
            else if (lowerCurrency.IndexOf("cfa franc") >= 0)
                currency = "BEA";
            else if (lowerCurrency.IndexOf("chilean peso") >= 0)
                currency = "CLP";
            else if (lowerCurrency.IndexOf("chinese yuan") >= 0)
                currency = "CNY";
            else if (lowerCurrency.IndexOf("colombian peso") >= 0)
                currency = "COP";
            else if (lowerCurrency.IndexOf("comoros franc") >= 0)
                currency = "KMF";
            else if (lowerCurrency.IndexOf("copper ounces") >= 0)
                currency = "XCP";
            else if (lowerCurrency.IndexOf("costa rica colon") >= 0)
                currency = "CRC";
            else if (lowerCurrency.IndexOf("croatian kuna") >= 0)
                currency = "HRK";
            else if (lowerCurrency.IndexOf("cuban peso") >= 0)
                currency = "CUP";
            else if (lowerCurrency.IndexOf("cyprus pound") >= 0)
                currency = "CYP";
            else if (lowerCurrency.IndexOf("czech koruna") >= 0)
                currency = "CZK";
            else if (lowerCurrency.IndexOf("danish krone") >= 0)
                currency = "DKK";
            else if (lowerCurrency.IndexOf("dijibouti franc") >= 0)
                currency = "DJF";
            else if (lowerCurrency.IndexOf("dominican peso") >= 0)
                currency = "DOP";
            else if (lowerCurrency.IndexOf("east caribbean dollar") >= 0)
                currency = "XCD";
            else if (lowerCurrency.IndexOf("ecuador sucre") >= 0)
                currency = "ECS";
            else if (lowerCurrency.IndexOf("egyptian pound") >= 0)
                currency = "EGP";
            else if (lowerCurrency.IndexOf("el salvador colon") >= 0)
                currency = "SVC";
            else if (lowerCurrency.IndexOf("eritrea nakfa") >= 0)
                currency = "ERN";
            else if (lowerCurrency.IndexOf("estonian kroon") >= 0)
                currency = "EEK";
            else if (lowerCurrency.IndexOf("ethiopian birr") >= 0)
                currency = "ETB";
            else if (lowerCurrency.IndexOf("euro") >= 0)
                currency = "EUR";
            else if (lowerCurrency.IndexOf("falkland islands pound") >= 0)
                currency = "FKP";
            else if (lowerCurrency.IndexOf("fiji dollar") >= 0)
                currency = "FJD";
            else if (lowerCurrency.IndexOf("gambian dalasi") >= 0)
                currency = "GMD";
            else if (lowerCurrency.IndexOf("ghanian cedi") >= 0)
                currency = "GHC";
            else if (lowerCurrency.IndexOf("gibraltar pound") >= 0)
                currency = "GIP";
            else if (lowerCurrency.IndexOf("gold ounces") >= 0)
                currency = "XAU";
            else if (lowerCurrency.IndexOf("guatemala quetzal") >= 0)
                currency = "GTQ";
            else if (lowerCurrency.IndexOf("guinea franc") >= 0)
                currency = "GNF";
            else if (lowerCurrency.IndexOf("guyana dollar") >= 0)
                currency = "GYD";
            else if (lowerCurrency.IndexOf("haiti gourde") >= 0)
                currency = "HTG";
            else if (lowerCurrency.IndexOf("honduras lempira") >= 0)
                currency = "HNL";
            else if (lowerCurrency.IndexOf("hong kong dollar") >= 0)
                currency = "HKD";
            else if (lowerCurrency.IndexOf("hungarian forint") >= 0)
                currency = "HUF";
            else if (lowerCurrency.IndexOf("iceland krona") >= 0)
                currency = "ISK";
            else if (lowerCurrency.IndexOf("indian rupee") >= 0)
                currency = "INR";
            else if (lowerCurrency.IndexOf("indonesian rupiah") >= 0)
                currency = "IDR";
            else if (lowerCurrency.IndexOf("iran rial") >= 0)
                currency = "IRR";
            else if (lowerCurrency.IndexOf("iraqi dinar") >= 0)
                currency = "IQD";
            else if (lowerCurrency.IndexOf("israeli shekel") >= 0)
                currency = "ILS";
            else if (lowerCurrency.IndexOf("jamaican dollar") >= 0)
                currency = "JMD";
            else if (lowerCurrency.IndexOf("japanese yen") >= 0)
                currency = "JPY";
            else if (lowerCurrency.IndexOf("jordanian dinar") >= 0)
                currency = "JOD";
            else if (lowerCurrency.IndexOf("kazakhstan tenge") >= 0)
                currency = "KZT";
            else if (lowerCurrency.IndexOf("kenyan shilling") >= 0)
                currency = "KES";
            else if (lowerCurrency.IndexOf("korean won") >= 0)
                currency = "KRW";
            else if (lowerCurrency.IndexOf("kuwaiti dinar") >= 0)
                currency = "KWD";
            else if (lowerCurrency.IndexOf("lao kip") >= 0)
                currency = "LAK";
            else if (lowerCurrency.IndexOf("latvian lat") >= 0)
                currency = "LVL";
            else if (lowerCurrency.IndexOf("lebanese pound") >= 0)
                currency = "LBP";
            else if (lowerCurrency.IndexOf("lesotho loti") >= 0)
                currency = "LSL";
            else if (lowerCurrency.IndexOf("liberian dollar") >= 0)
                currency = "LRD";
            else if (lowerCurrency.IndexOf("libyan dinar") >= 0)
                currency = "LYD";
            else if (lowerCurrency.IndexOf("lithuanian lita") >= 0)
                currency = "LTL";
            else if (lowerCurrency.IndexOf("macau pataca") >= 0)
                currency = "MOP";
            else if (lowerCurrency.IndexOf("macedonian denar") >= 0)
                currency = "MKD";
            else if (lowerCurrency.IndexOf("malagasy ariary") >= 0)
                currency = "MGA";
            else if (lowerCurrency.IndexOf("malawi kwacha") >= 0)
                currency = "MWK";
            else if (lowerCurrency.IndexOf("malaysian ringgit") >= 0)
                currency = "MYR";
            else if (lowerCurrency.IndexOf("maldives rufiyaa") >= 0)
                currency = "MVR";
            else if (lowerCurrency.IndexOf("maltese lira") >= 0)
                currency = "MTL";
            else if (lowerCurrency.IndexOf("mauritania ougulya") >= 0)
                currency = "MRO";
            else if (lowerCurrency.IndexOf("mauritius rupee") >= 0)
                currency = "MUR";
            else if (lowerCurrency.IndexOf("mexican peso") >= 0)
                currency = "MXN";
            else if (lowerCurrency.IndexOf("moldovan leu") >= 0)
                currency = "MDL";
            else if (lowerCurrency.IndexOf("mongolian tugrik") >= 0)
                currency = "MNT";
            else if (lowerCurrency.IndexOf("moroccan dirham") >= 0)
                currency = "MAD";
            else if (lowerCurrency.IndexOf("mozambique metical") >= 0)
                currency = "MZN";
            else if (lowerCurrency.IndexOf("myanmar kyat") >= 0)
                currency = "MMK";
            else if (lowerCurrency.IndexOf("namibian dollar") >= 0)
                currency = "NAD";
            else if (lowerCurrency.IndexOf("nepalese rupee") >= 0)
                currency = "NPR";
            else if (lowerCurrency.IndexOf("neth antilles guilder") >= 0)
                currency = "ANG";
            else if (lowerCurrency.IndexOf("new turkish lira") >= 0)
                currency = "TRY";
            else if (lowerCurrency.IndexOf("new zealand dollar") >= 0)
                currency = "NZD";
            else if (lowerCurrency.IndexOf("new zimbabwe dollar") >= 0)
                currency = "ZWN";
            else if (lowerCurrency.IndexOf("nicaragua cordoba") >= 0)
                currency = "NIO";
            else if (lowerCurrency.IndexOf("nigerian naira") >= 0)
                currency = "NGN";
            else if (lowerCurrency.IndexOf("north korean won") >= 0)
                currency = "KPW";
            else if (lowerCurrency.IndexOf("norwegian krone") >= 0)
                currency = "NOK";
            else if (lowerCurrency.IndexOf("omani rial") >= 0)
                currency = "OMR";
            else if (lowerCurrency.IndexOf("pacific franc") >= 0)
                currency = "XPF";
            else if (lowerCurrency.IndexOf("pakistani rupee") >= 0)
                currency = "PKR";
            else if (lowerCurrency.IndexOf("palladium ounces") >= 0)
                currency = "XPD";
            else if (lowerCurrency.IndexOf("panama balboa") >= 0)
                currency = "PAB";
            else if (lowerCurrency.IndexOf("papua new guinea kina") >= 0)
                currency = "PGK";
            else if (lowerCurrency.IndexOf("paraguayan guarani") >= 0)
                currency = "PYG";
            else if (lowerCurrency.IndexOf("peruvian nuevo sol") >= 0)
                currency = "PEN";
            else if (lowerCurrency.IndexOf("philippine peso") >= 0)
                currency = "PHP";
            else if (lowerCurrency.IndexOf("platinum ounces") >= 0)
                currency = "XPT";
            else if (lowerCurrency.IndexOf("polish zloty") >= 0)
                currency = "PLN";
            else if (lowerCurrency.IndexOf("qatar rial") >= 0)
                currency = "QAR";
            else if (lowerCurrency.IndexOf("romanian leu") >= 0)
                currency = "ROL";
            else if (lowerCurrency.IndexOf("romanian new leu") >= 0)
                currency = "RON";
            else if (lowerCurrency.IndexOf("russian rouble") >= 0)
                currency = "RUB";
            else if (lowerCurrency.IndexOf("rwanda franc") >= 0)
                currency = "RWF";
            else if (lowerCurrency.IndexOf("samoa tala") >= 0)
                currency = "WST";
            else if (lowerCurrency.IndexOf("sao tome dobra") >= 0)
                currency = "STD";
            else if (lowerCurrency.IndexOf("saudi arabian riyal") >= 0)
                currency = "SAR";
            else if (lowerCurrency.IndexOf("seychelles rupee") >= 0)
                currency = "SCR";
            else if (lowerCurrency.IndexOf("sierra leone leone") >= 0)
                currency = "SLL";
            else if (lowerCurrency.IndexOf("singapore dollar") >= 0)
                currency = "SGD";
            else if (lowerCurrency.IndexOf("slovak koruna") >= 0)
                currency = "SKK";
            else if (lowerCurrency.IndexOf("slovenian tolar") >= 0)
                currency = "SIT";
            else if (lowerCurrency.IndexOf("solomon islands dollar") >= 0)
                currency = "SBD";
            else if (lowerCurrency.IndexOf("somali shilling") >= 0)
                currency = "SOS";
            else if (lowerCurrency.IndexOf("south african rand") >= 0)
                currency = "ZAR";
            else if (lowerCurrency.IndexOf("sri lanka rupee") >= 0)
                currency = "LKR";
            else if (lowerCurrency.IndexOf("st helena pound") >= 0)
                currency = "SHP";
            else if (lowerCurrency.IndexOf("sudanese dinar") >= 0)
                currency = "SDD";
            else if (lowerCurrency.IndexOf("surinamese dollar") >= 0)
                currency = "SRD";
            else if (lowerCurrency.IndexOf("swaziland lilageni") >= 0)
                currency = "SZL";
            else if (lowerCurrency.IndexOf("swedish krona") >= 0)
                currency = "SEK";
            else if (lowerCurrency.IndexOf("swiss franc") >= 0)
                currency = "CHF";
            else if (lowerCurrency.IndexOf("syrian pound") >= 0)
                currency = "SYP";
            else if (lowerCurrency.IndexOf("taiwan dollar") >= 0)
                currency = "TWD";
            else if (lowerCurrency.IndexOf("tanzanian shilling") >= 0)
                currency = "TZS";
            else if (lowerCurrency.IndexOf("thai baht") >= 0)
                currency = "THB";
            else if (lowerCurrency.IndexOf("tonga") >= 0)
                currency = "TOP";
            else if (lowerCurrency.IndexOf("trinidad & tobago dollar") >= 0)
                currency = "TTD";
            else if (lowerCurrency.IndexOf("tunisian dinar") >= 0)
                currency = "TND";
            else if (lowerCurrency.IndexOf("u.s. dollar") >= 0)
                currency = "USD";
            else if (lowerCurrency.IndexOf("uae dirham") >= 0)
                currency = "AED";
            else if (lowerCurrency.IndexOf("ugandan shilling") >= 0)
                currency = "UGX";
            else if (lowerCurrency.IndexOf("ukraine hryvnia") >= 0)
                currency = "UAH";
            else if (lowerCurrency.IndexOf("uruguayan new peso") >= 0)
                currency = "UYU";
            else if (lowerCurrency.IndexOf("vanuatu vatu") >= 0)
                currency = "VUV";
            else if (lowerCurrency.IndexOf("venezuelan bolivar") >= 0)
                currency = "VEB";
            else if (lowerCurrency.IndexOf("vietnam dong") >= 0)
                currency = "VND";
            else if (lowerCurrency.IndexOf("yemen riyal") >= 0)
                currency = "YER";
            else if (lowerCurrency.IndexOf("zambian kwacha") >= 0)
                currency = "ZMK";
            else if (lowerCurrency.IndexOf("zimbabwe dollar") >= 0)
                currency = "ZWD";
            else if (lowerCurrency.IndexOf("american dollars") >= 0)
                currency = "USD";

            //Finding Currency with Symbols
            else if (lowerCurrency.IndexOf("$") >= 0)
                currency = "USD";
            else if (lowerCurrency.IndexOf("€") >= 0)
                currency = "EUR";
            else if (lowerCurrency.IndexOf("bz$") >= 0)
                currency = "BZD";
            else if (lowerCurrency.IndexOf("$b") >= 0)
                currency = "BOB";
            else if (lowerCurrency.IndexOf("r$") >= 0)
                currency = "BRL";
            else if (lowerCurrency.IndexOf("kn") >= 0)
                currency = "HRK";
            //if (_Currency.IndexOf("₱") >= 0)
            //    _Currency = "CUP";
            else if (lowerCurrency.IndexOf("kč") >= 0)
                currency = "CZK";
            else if (lowerCurrency.IndexOf("₨") >= 0)
                currency = "INR";
            else if (lowerCurrency.IndexOf("rd$") >= 0)
                currency = "DOP";
            else if (lowerCurrency.IndexOf("£") >= 0)
                currency = "GBP";
            else if (lowerCurrency.IndexOf("£") >= 0)
                currency = "GBP";
            else if (lowerCurrency.IndexOf("¥") >= 0)
                currency = "JPY";
            else if (lowerCurrency.IndexOf("rm") >= 0)
                currency = "MYR";
            else if (lowerCurrency.IndexOf("z$") >= 0)
                currency = "ZWD";
            else if (lowerCurrency.IndexOf("лв") >= 0)
                currency = "UZS";
            else if (lowerCurrency.IndexOf("лв") >= 0)
                currency = "UZS";
            else if (lowerCurrency.IndexOf("euro") >= 0)
                currency = "EUR";
            else if (lowerCurrency.IndexOf("р.") >= 0)
                currency = "RUB";
            else if (lowerCurrency.IndexOf("USD") >= 0)
                currency = "USD";
            else if (lowerCurrency.IndexOf("₹") >= 0)
                currency = "INR";
            return currency;
        }
    }
}
